stages:
  download:
    cmd: python scripts/data/download.py
    deps:
      - scripts/data/download.py
      - configs/data.yaml
      - src/bbb_classifier/data/hf_peptides.py
    outs:
      - data/bbb-peptides/peptides.parquet

  train:
    cmd: python scripts/classifier/train.py --exp ${experiment} --data-config configs/data.yaml --train-config configs/train.yaml --output-root artifacts
    deps:
      - scripts/classifier/train.py
      - configs/data.yaml
      - configs/train.yaml
      - ${experiment}
      - data/bbb-peptides/peptides.parquet
    outs:
      - artifacts/models

  evaluate:
    cmd: python scripts/classifier/evaluate.py --run-dir ${run_dir} --dataset-path data/bbb-peptides/peptides.parquet
    deps:
      - scripts/classifier/evaluate.py
      - ${run_dir}
      - data/bbb-peptides/peptides.parquet
    metrics:
      - ${run_dir}/evaluation_metrics.json
