stages:
  download:
    cmd: python -m bbb_classifier download-data
    deps:
      - src/bbb_classifier/run.py
      - src/bbb_classifier/dataset.py
      - configs/data.yaml
    outs:
      - data/bbb-peptides/peptides.parquet

  train:
    cmd: python -m bbb_classifier train --exp ${experiment} --data-config configs/data.yaml --train-config configs/train.yaml --output-root artifacts
    deps:
      - src/bbb_classifier/run.py
      - configs/data.yaml
      - configs/train.yaml
      - ${experiment}
      - data/bbb-peptides/peptides.parquet
    outs:
      - artifacts/models

  evaluate:
    cmd: python -m bbb_classifier evaluate --run-dir ${run_dir} --dataset-path data/bbb-peptides/peptides.parquet
    deps:
      - src/bbb_classifier/run.py
      - ${run_dir}
      - data/bbb-peptides/peptides.parquet
    metrics:
      - ${run_dir}/evaluation_metrics.json
